version: '3.4'

services:
  web-proxy:
    container_name: web-proxy
    image: nginx:1.13.12
    volumes:
      - ./ReverseProxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../../milenkoraic-certs/milenkoraic.me.crt:/etc/ssl/certs/milenkoraic.me.crt:ro
      - ../../milenkoraic-certs/milenkoraic.me.key:/etc/ssl/certs/milenkoraic.me.key:ro

  milenkoraic-web:
    container_name: milenkoraic-web
    image: milenkoraic/milenkoraic:1.0.0
    build:
      context: .
      dockerfile: Source/CleanArch.Client.MVC/Dockerfile